---
title: Структура (зависимости) проектов в решении
---
classDiagram
note for DbPostgreLib "Если используется другая СУБД, тогда указатели  от [ServerLib] [TelegramBotService], [HelpdeskService] и [RemoteCallLib] должны ссылаться на соответсвующую библиотеку: [DbPostgreLib] или [DbMySQLLib]"
    SharedLib <|-- CodegeneratorLib
    SharedLib <|-- IdentityLib
    SharedLib <|-- DbLayerLib
    BlazorLib <|-- ToolsMauiApp
    SharedLib : Общие модели
    IdentityLib <|-- ServerLib
    DbPostgreLib <|-- ServerLib
    RemoteCallLib <|-- ServerLib
    RemoteCallLib <|-- CommerceService
    RemoteCallLib <|-- ApiRestService
    CodegeneratorLib <|-- BlazorLib
    HtmlGenerator <|-- CodegeneratorLib
    DbLayerLib <|-- DbPostgreLib
    DbLayerLib <|-- DbSqliteLib
    DbLayerLib <|-- DbMySQLLib
	DbPostgreLib <|-- RemoteCallLib
    BlankBlazorApp_Client  <|-- BlankBlazorApp
	BlazorWebLib  <|-- BlankBlazorApp
	ServerLib  <|-- BlankBlazorApp
	IdentityService  <|-- BlankBlazorApp
    RemoteCallLib <|-- TelegramBotService
	DbPostgreLib <|-- TelegramBotService
    RemoteCallLib <|-- StorageService
    RemoteCallLib <|-- ConstructorService
    RemoteCallLib <|-- HelpdeskService
	DbPostgreLib <|-- HelpdeskService
    BlazorLib <|-- BlazorWebLib
    BlazorLib <|-- BlankBlazorApp_Client
    	
    class CodegeneratorLib{
        Генератор исходников для Web конструктора
    }
    class IdentityLib{
        Контекст пакета Identity (авторизация)
    }
    class DbLayerLib{
        Абстракция над Мульти-СУБД
    }
    class ServerLib{
        Backend для BlankBlazorApp
    }
    class BlazorLib{
        Blazor UI Компоненты
    }
    class DbSqliteLib{
        Sqlite
    }
    class DbPostgreLib{
        PostgreSQL
    }
    class DbMySQLLib{
        MySQL
    }
    class RemoteCallLib{
        Трансмиссия
    }
    class BlankBlazorApp_Client["BlankBlazorApp.Client"]{
        CSR Blazor WebAssembly
    }
    class BlazorWebLib{
        SSR Blazor Server
    }

    class BlankBlazorApp{
        @Микросервис - Вебсервер/ServerSideRender
    }
    class IdentityService{
        @Микросервис - Пользователи/Регистрация/Авторизация
    }
    class StorageService{
        @Микросервис - Файлы/Тэги/CMS
    }
    class ConstructorService{
        @Микросервис - ВебКонструктор/ВебФормы
    }
    class TelegramBotService["TelegramBotService"]{
        @Микросервис - TelegramBot/Wappi
    }
    class HelpdeskService{
        @Микросервис - Хелпдеск/Сервисдеск/Таскменеджер
    }
    class CommerceService{
        @Микросервис - Склад/Продажи/Расписания
    }
    class ApiRestService{
        @Микросервис - Api/Rest
    }
    class ToolsMauiApp{
      @Клиент - Win/Android
    }

    class HtmlGenerator{
        Внешний репозиторий
    }