//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodegeneratorLib.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodegeneratorLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @page &quot;/documents-journal/{DocumentType:string}&quot;
        ///
        ///@inherits BlazorBusyComponentBaseModel
        ///
        ///&lt;h3&gt;JournalUniversalComponent&lt;/h3&gt;
        ///
        ///@code {
        ///    [Parameter]
        ///    public required string DocumentType { get; set; }
        ///
        ///}.
        /// </summary>
        internal static string JournalUniversalComponent_razor {
            get {
                return ResourceManager.GetString("JournalUniversalComponent_razor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ////////////////////////////////////////////////
        ///// © https://github.com/badhitman - @fakegov 
        ///////////////////////////////////////////////////
        ///
        ///using BlazorLib;
        ///
        ///namespace BlazorWebLib.Components;
        ///
        ////// &lt;summary&gt;
        ////// Журнал документов (универсальный)
        ////// &lt;/summary&gt;
        ///public partial class JournalUniversalComponent : BlazorBusyComponentBaseModel
        ///{
        ///
        ///}.
        /// </summary>
        internal static string JournalUniversalComponent_razor_cs {
            get {
                return ResourceManager.GetString("JournalUniversalComponent_razor_cs", resourceCulture);
            }
        }
    }
}
